name: Build app - recipe environment

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        name: Setup Java 21
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Build test apk mode debug
        run: bash ./gradlew test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        name: Setup Java 21
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Build apk file
        run: bash ./gradlew build