name: Validation Pull Request

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Android SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build de l'application Android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Lance des tests unitaires Android
        run: |
          ./gradlew testDebugUnitTest

      - name: Place l'APK dans un dossier
        run: |
          mkdir artifacts
          cp app/build/outputs/apk/debug/app-debug.apk artifacts/
          ls artifacts/

  validation_pull_request:
    runs-on: ubuntu-latest
    needs: validation
    if: github.event_name == 'pull_request'

    steps:
      - name: Validation de la pipeline
        run: |
          # Insérer ici la logique pour valider la pipeline
          echo "Validation de la pipeline associée à la pull request..."
