name: Build main - recipe

on:
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

concurrency:
  group: pr-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        name: Setup Java 21
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Run tests
        run: bash ./gradlew test

      - name: Build apk file
        run: bash ./gradlew build